### ISSUE TITLE
Unable to upload image

### ISSUE THREAD

**Issue by calverp** [BookStackApp/BookStack#137]
I'll begin by stating that this is very likely user error on my part. I'm running Bookstack from Windows/IIS and everything is working fine except for uploading images. If I drag a file into the upload box, a small thumbnail appears with the name and size of the file, and a red hover over box with a bunch of HTML appears, but the image doesn't save as expected.
I've checked the error log file and it is generating the attach stack trace indicating the it is missing a file name. I've confirmed the image/name is fine by uploading to your demo site fine.
Any assistance would be appreciated,
Thanks.
[bookstack.txt](https://github.com/ssddanbrown/BookStack/files/341222/bookstack.txt)

**Comment by patoroco** [comment]
I think that this was solved in last releases, isn't it @ssddanbrown?

**Comment by mrb2590** [comment]
I am having the same issue, I granted all users full permissions on the folder too and still getting this.

**Comment by mrb2590** [comment]
From the error log:
[2017-05-17 14:05:21] production.ERROR: exception 'ErrorException' with message 'file_get_contents(): Filename cannot be empty' in C:\inetpub\wwwroot\wiki.example.com\app\Services\ImageService.php:45

**Comment by ssddanbrown** [comment]
@mrb2590 Any additional details would be great, Are you also on IIS? What version is you BookStack instance? What PHP version are you on?

**Comment by mrb2590** [comment]
@ssddanbrown Yup I am also on IIS. I can't check right now but I believe it is the latest version of BookStack I just installed it earlier this week and installed the release version. I am using php 5.6. I was looking into it earlier and saw in the ImageService class it is calling uploadedfile->getRealPath() into file_get_contents and getRealPath is returning false. The image file is in fact in the windows temp folder and did upload successfully but I guess saving it is where it's breaking. I can get more information to you on Monday. Hope this helps! Let me know what else you may need.

**Comment by RexSeven** [comment]
I've had the same issue with image uploads on wordpress installs in IIS. To fix this you need to change the permissions on your temp folder. http://chris.wastedhalo.com/2011/01/wordpress-upload-permissions-on-iis-7-fix/

**Comment by mrb2590** [comment]
@RexSeven My hopes were up but unfortunately this did not work for me... It looks like inside app/Services/ImageService.php on line 46` $imageData = file_get_contents($uploadedFile->getRealPath()); `is failing because getRealPath is returning false. The file is in the temp folder though. If I replace That line with this: `$imageData = file_get_contents($uploadedFile->getPathName());` it does indeed work. So it's not a fix, but a workaround for now. I hate to touch the source code here to get this to work, but SplFileInfo::getRealPath() seems to be failing for some reason.

**Comment by Abijeet** [comment]
@mrb2590 - Same happened with me and I had to touch the source code.

**Comment by Abijeet** [comment]
Another user reported an issue here - https://bugs.php.net/bug.php?id=74411&edit=1

**Comment by ssddanbrown** [comment]
Thank you for opening this issue. As part of an issue clean-up we're closing off older support issues that may be outdated or irrelevant so therefore I am closing this issue.

If the issue remains and it is one you are still seeking to actively solve please ensure it is still not apparent on the latest version of BookStack then open up a new issue referencing this one.

Sorry if we were not able to solve your original request.

**Comment by Zabrielle** [comment]
Add permission for your IUSR in Windows temp folder
