### ISSUE TITLE
Unable to edit the page content 

### ISSUE THREAD

**Issue by namannj46** [BookStackApp/BookStack#4426]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hi, there is no content page is showing when i visit on page edit section.
Not able to edit or add new content on the pages [
<img width="950" alt="image" src="https://github.com/BookStackApp/BookStack/assets/140008506/d2010bff-6780-4eaa-ba17-6f143bb5f48b">
](url)

### Exact BookStack Version

v23.05.2

### Hosting Environment

ubuntu 22.04

**Comment by ssddanbrown** [comment]
Hi @namannj46,
Please can you describe your scenario a bit more:

- Is this a new fresh instance?
- Or is this a new issue on an existing instance that worked before?
- How did you install BookStack?
- Do you have any customizations set or any hacks applied?

**Comment by namannj46** [comment]
Yeah sure,

I have installed bookstack application [BookStack v23.05.2](https://github.com/BookStackApp/BookStack/releases) on my ec2 ubuntu(22.04) instance.
with this following doc 
(https://www.bookstackapp.com/docs/admin/installation/#ubuntu-2204)

In starting we are able to edit and change the content in pages. but now the title content page is not showing any content when we are trying to edit or add.
**_Or is this a new issue on an existing instance that worked before?_**
it is new issue 

### **Do you have any customizations set or any hacks applied?**
yes we enable google auth in it.

Please help here

**Comment by yogikortisa** [comment]
I have the same problem with my instances, is there any solutions for this? the content of page always blank/empty whenever create new page or edit existing page.

- Is this a new fresh instance?
yes [BookStack v23.06.2](https://github.com/BookStackApp/BookStack/releases) docker version on ubuntu server 22.04 instance

- Or is this a new issue on an existing instance that worked before?
yes, it's last worked 6 days ago in my instance based on the history

- How did you install BookStack?
[docker install](https://www.bookstackapp.com/docs/admin/installation/#docker)
https://github.com/linuxserver/docker-bookstack#usage

- Do you have any customizations set or any hacks applied?
the database is using external db connection

**Comment by namannj46** [comment]
Hi Yogi,


I managed to resolve my issue using CSP. Could you kindly verify whether a Content Security Policy is enabled for Bookstack? I suspect that CSP might be causing the current problem I'm facing.

One more thing please inspect on the page where you are getting error, check the error it is showing

**Comment by yogikortisa** [comment]
Hello @namannj46 I think my problem is the same as the CSP error, the error from console log is: 
`Refused to set the document's base URI to '' because it violates the following Content Security Policy directive: "base-uri 'self'".`
Can you tell me how exactly step you take to solve the problem? thank you anyway for your info..

**Comment by namannj46** [comment]
Please add these line in bookstack.conf file inside the site-enabled folder of apache2

Header add Content-Security-Policy " default-src 'self' ; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self'; connect-src 'self'; object-src 'none'; media-src 'self';

**Comment by yogikortisa** [comment]
I use docker version from: https://github.com/linuxserver/docker-bookstack that use nginx and when I add these line with change Header add to add_header (nginx syntax) the problem still persist. I checked on https://demo.bookstackapp.com/ the console log is the same but the problem with not send posting content is not there. I doubt is CSP caused this problem or not. I want try to disable CSP setting but I  have checked all place on the container but not found any CSP settings there..

**Comment by ssddanbrown** [comment]
@yogikortisa 

- Have you properly set a `APP_URL` parameter for the container to match the URL that BookStack is being used on?
- Do you see any other (red) errors in the browser development console log after reloading the edit page in the non-working state?

@namannj46  Just a warning, Those CSP lines will remove a lot of the security controls BookStack adds via CSP.

**Comment by yogikortisa** [comment]
> @yogikortisa
> 
> * Have you properly set a `APP_URL` parameter for the container to match the URL that BookStack is being used on?
> * Do you see any other (red) errors in the browser development console log after reloading the edit page in the non-working state?
> 
> @namannj46 Just a warning, Those CSP lines will remove a lot of the security controls BookStack adds via CSP.

Oh yes my bad. I figured out the problem is on APP_URL, I set http instead https, thank you @ssddanbrown

**Comment by ssddanbrown** [comment]
@yogikortisa Good to hear that worked.

Since both of you have mentioned this being resolved in some way, I'll go ahead and close this off.

**Comment by yogikortisa** [comment]
Hello @ssddanbrown recently my problem is back again, I checked all the settings including APP_URL but the behaviour is the same, the problem is I can not view the content of a page whenever when on the add form / edit form of a page. But when I used Burp Suite's internal browser (chromium) when opened Burp Suite and access my BookStack instance, there is no problem! I checked the request & response is the same between normal browser and Burp's browser. Any clue?? I really confused about this weird behavior.. @ssddanbrown @namannj46

**Comment by ssddanbrown** [comment]
@yogikortisa Do you see any other (red) errors in the browser development console log after reloading the edit page in the non-working state?

**Comment by yogikortisa** [comment]
> @yogikortisa Do you see any other (red) errors in the browser development console log after reloading the edit page in the non-working state?

below is the ss of my console.log when in the non-working state of the edit page..

![image](https://github.com/BookStackApp/BookStack/assets/11523249/f5fb7933-88ed-4cbb-9850-463bbda08728)

**Comment by yogikortisa** [comment]
@ssddanbrown I just discovered what caused this problem, I think it's the conf on my load balancer changes in my case, I revoke the change and after that clear cache on the browser, the problem is gone. Thank you.
